/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DecodeSTORM_ */

#ifndef _Included_DecodeSTORM_
#define _Included_DecodeSTORM_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DecodeSTORM_
 * Method:    lm_Convert
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1Convert
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetInLoc1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1GetInLoc1
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetInLoc2
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1GetInLoc2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetRoiLocPara
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetRoiLocPara
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRoiLoc1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1GetRoiLoc1
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRoiLoc2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1GetRoiLoc2
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetSaveDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetSaveDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetFilteringPara
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetFilteringPara
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetDriftCorrPara
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetDriftCorrPara
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetDBSCANPara
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetDBSCANPara
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetSpatialStatisticsPara
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetSpatialStatisticsPara
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SetColocalizationPara
 * Signature: (FFFDD)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SetColocalizationPara
  (JNIEnv *, jclass,  jfloat, jfloat, jfloat, jdouble, jdouble);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetChan1Loc
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetChan1Loc
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetChan2Loc
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetChan2Loc
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetChan1RoiLoc
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetChan1RoiLoc
(JNIEnv*, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetChan2RoiLoc
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetChan2RoiLoc
(JNIEnv*, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetScatImInfo
 * Signature: (ZZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetScatImInfo
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetScatRoiImInfo
 * Signature: (ZZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetScatRoiImInfo
(JNIEnv*, jclass, jboolean, jboolean);
/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetCh1SMLMImage
 * Signature: (FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetCh1SMLMImage
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetCh2SMLMImage
 * Signature: (FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetCh2SMLMImage
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetMaxDispVal
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_DecodeSTORM_1_lm_1GetMaxDispVal
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRenderImageInf
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DecodeSTORM_1_lm_1GetRenderImageInf
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_StartDriftCorr
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1StartDriftCorr
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_Filtering
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1Filtering
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRdfIm
 * Signature: (III)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetRdfIm
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRdfImInfo
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetRdfImInfo
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRipleyHIm
 * Signature: (III)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_DecodeSTORM_1_lm_1GetRipleyHIm
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetRipleyImInfo
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetRipleyImInfo
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SaveRipleyResult
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SaveRipleyResult
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetDbscanImCh1
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_DecodeSTORM_1_lm_1GetDbscanImCh1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetDbscanImCh2
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_DecodeSTORM_1_lm_1GetDbscanImCh2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetDbscanImInfo
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_DecodeSTORM_1_lm_1GetDbscanImInfo
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SaveDbscanResult
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SaveDbscanResult
  (JNIEnv *, jclass, jstring);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_VoronoiDiagramCh1
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1VoronoiDiagramCh1
  (JNIEnv *, jclass,jstring, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_VoronoiDiagramCh2
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1VoronoiDiagramCh2
  (JNIEnv *, jclass,jstring, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_IsSaveVoronoiResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1IsSaveVoronoiResult
  (JNIEnv *, jclass, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_Colocalization
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1Colocalization
  (JNIEnv *, jclass, jint);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetCBC1Hist
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_DecodeSTORM_1_lm_1GetCBC1Hist
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetCBC2Hist
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_DecodeSTORM_1_lm_1GetCBC2Hist
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_GetCBCHistInfo
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_DecodeSTORM_1_lm_1GetCBCHistInfo
  (JNIEnv *, jclass);

/*
 * Class:     DecodeSTORM_
 * Method:    lm_SaveColoclizationResult
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DecodeSTORM_1_lm_1SaveColoclizationResult
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
